version: "3"
services:
  math_solver_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math_solver_app
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - ./database:/users.db

volumes:
    data:
      driver: local
